#!/bin/bash
cp ${HIGHS_HOME}/build/lib/libhighs.so ./
cd src/main/java/highs
cc -O3 -fPIC -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux -I${HIGHS_HOME}/highs -I${HIGHS_HOME}/build -c swig_java_highs_wrap.cxx
cxx -shared -o ../../../../libhighswrap.so swig_java_highs_wrap.o -L../../../../ -lhighs
