/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class GlpsolCostRowLocation {
  public final static GlpsolCostRowLocation kGlpsolCostRowLocationLast = new GlpsolCostRowLocation("kGlpsolCostRowLocationLast", highsJNI.kGlpsolCostRowLocationLast_get());
  public final static GlpsolCostRowLocation kGlpsolCostRowLocationNone = new GlpsolCostRowLocation("kGlpsolCostRowLocationNone");
  public final static GlpsolCostRowLocation kGlpsolCostRowLocationNoneIfEmpty = new GlpsolCostRowLocation("kGlpsolCostRowLocationNoneIfEmpty");
  public final static GlpsolCostRowLocation kGlpsolCostRowLocationMin = new GlpsolCostRowLocation("kGlpsolCostRowLocationMin", highsJNI.kGlpsolCostRowLocationMin_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GlpsolCostRowLocation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GlpsolCostRowLocation.class + " with value " + swigValue);
  }

  private GlpsolCostRowLocation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GlpsolCostRowLocation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GlpsolCostRowLocation(String swigName, GlpsolCostRowLocation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GlpsolCostRowLocation[] swigValues = { kGlpsolCostRowLocationLast, kGlpsolCostRowLocationNone, kGlpsolCostRowLocationNoneIfEmpty, kGlpsolCostRowLocationMin };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

