/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HighsPresolveRuleLog {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HighsPresolveRuleLog(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighsPresolveRuleLog obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HighsPresolveRuleLog obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HighsPresolveRuleLog(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCall(int value) {
    highsJNI.HighsPresolveRuleLog_call_set(swigCPtr, this, value);
  }

  public int getCall() {
    return highsJNI.HighsPresolveRuleLog_call_get(swigCPtr, this);
  }

  public void setCol_removed(int value) {
    highsJNI.HighsPresolveRuleLog_col_removed_set(swigCPtr, this, value);
  }

  public int getCol_removed() {
    return highsJNI.HighsPresolveRuleLog_col_removed_get(swigCPtr, this);
  }

  public void setRow_removed(int value) {
    highsJNI.HighsPresolveRuleLog_row_removed_set(swigCPtr, this, value);
  }

  public int getRow_removed() {
    return highsJNI.HighsPresolveRuleLog_row_removed_get(swigCPtr, this);
  }

  public HighsPresolveRuleLog() {
    this(highsJNI.new_HighsPresolveRuleLog(), true);
  }

}
