/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public interface highsConstants {
  public final static String HIGHSINT_FORMAT = highsJNI.HIGHSINT_FORMAT_get();
}
