/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsDebugLevel {
  public final static HighsDebugLevel kHighsDebugLevelNone = new HighsDebugLevel("kHighsDebugLevelNone", highsJNI.kHighsDebugLevelNone_get());
  public final static HighsDebugLevel kHighsDebugLevelCheap = new HighsDebugLevel("kHighsDebugLevelCheap");
  public final static HighsDebugLevel kHighsDebugLevelCostly = new HighsDebugLevel("kHighsDebugLevelCostly");
  public final static HighsDebugLevel kHighsDebugLevelExpensive = new HighsDebugLevel("kHighsDebugLevelExpensive");
  public final static HighsDebugLevel kHighsDebugLevelMin = new HighsDebugLevel("kHighsDebugLevelMin", highsJNI.kHighsDebugLevelMin_get());
  public final static HighsDebugLevel kHighsDebugLevelMax = new HighsDebugLevel("kHighsDebugLevelMax", highsJNI.kHighsDebugLevelMax_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsDebugLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsDebugLevel.class + " with value " + swigValue);
  }

  private HighsDebugLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsDebugLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsDebugLevel(String swigName, HighsDebugLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsDebugLevel[] swigValues = { kHighsDebugLevelNone, kHighsDebugLevelCheap, kHighsDebugLevelCostly, kHighsDebugLevelExpensive, kHighsDebugLevelMin, kHighsDebugLevelMax };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

