/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HighsIllConditioningRecord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HighsIllConditioningRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighsIllConditioningRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HighsIllConditioningRecord obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HighsIllConditioningRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIndex(int value) {
    highsJNI.HighsIllConditioningRecord_index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return highsJNI.HighsIllConditioningRecord_index_get(swigCPtr, this);
  }

  public void setMultiplier(double value) {
    highsJNI.HighsIllConditioningRecord_multiplier_set(swigCPtr, this, value);
  }

  public double getMultiplier() {
    return highsJNI.HighsIllConditioningRecord_multiplier_get(swigCPtr, this);
  }

  public HighsIllConditioningRecord() {
    this(highsJNI.new_HighsIllConditioningRecord(), true);
  }

}
