/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsDebugStatus {
  public final static HighsDebugStatus kNotChecked = new HighsDebugStatus("kNotChecked", highsJNI.HighsDebugStatus_kNotChecked_get());
  public final static HighsDebugStatus kOk = new HighsDebugStatus("kOk");
  public final static HighsDebugStatus kSmallError = new HighsDebugStatus("kSmallError");
  public final static HighsDebugStatus kWarning = new HighsDebugStatus("kWarning");
  public final static HighsDebugStatus kLargeError = new HighsDebugStatus("kLargeError");
  public final static HighsDebugStatus kError = new HighsDebugStatus("kError");
  public final static HighsDebugStatus kExcessiveError = new HighsDebugStatus("kExcessiveError");
  public final static HighsDebugStatus kLogicalError = new HighsDebugStatus("kLogicalError");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsDebugStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsDebugStatus.class + " with value " + swigValue);
  }

  private HighsDebugStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsDebugStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsDebugStatus(String swigName, HighsDebugStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsDebugStatus[] swigValues = { kNotChecked, kOk, kSmallError, kWarning, kLargeError, kError, kExcessiveError, kLogicalError };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

