/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HighsFiles {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HighsFiles(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighsFiles obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HighsFiles obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HighsFiles(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEmpty(boolean value) {
    highsJNI.HighsFiles_empty_set(swigCPtr, this, value);
  }

  public boolean getEmpty() {
    return highsJNI.HighsFiles_empty_get(swigCPtr, this);
  }

  public void setRead_solution_file(String value) {
    highsJNI.HighsFiles_read_solution_file_set(swigCPtr, this, value);
  }

  public String getRead_solution_file() {
    return highsJNI.HighsFiles_read_solution_file_get(swigCPtr, this);
  }

  public void setRead_basis_file(String value) {
    highsJNI.HighsFiles_read_basis_file_set(swigCPtr, this, value);
  }

  public String getRead_basis_file() {
    return highsJNI.HighsFiles_read_basis_file_get(swigCPtr, this);
  }

  public void setWrite_model_file(String value) {
    highsJNI.HighsFiles_write_model_file_set(swigCPtr, this, value);
  }

  public String getWrite_model_file() {
    return highsJNI.HighsFiles_write_model_file_get(swigCPtr, this);
  }

  public void setWrite_iis_model_file(String value) {
    highsJNI.HighsFiles_write_iis_model_file_set(swigCPtr, this, value);
  }

  public String getWrite_iis_model_file() {
    return highsJNI.HighsFiles_write_iis_model_file_get(swigCPtr, this);
  }

  public void setWrite_solution_file(String value) {
    highsJNI.HighsFiles_write_solution_file_set(swigCPtr, this, value);
  }

  public String getWrite_solution_file() {
    return highsJNI.HighsFiles_write_solution_file_get(swigCPtr, this);
  }

  public void setWrite_basis_file(String value) {
    highsJNI.HighsFiles_write_basis_file_set(swigCPtr, this, value);
  }

  public String getWrite_basis_file() {
    return highsJNI.HighsFiles_write_basis_file_get(swigCPtr, this);
  }

  public void clear() {
    highsJNI.HighsFiles_clear(swigCPtr, this);
  }

  public HighsFiles() {
    this(highsJNI.new_HighsFiles(), true);
  }

}
