/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsLogType {
  public final static HighsLogType kInfo = new HighsLogType("kInfo", highsJNI.HighsLogType_kInfo_get());
  public final static HighsLogType kDetailed = new HighsLogType("kDetailed");
  public final static HighsLogType kVerbose = new HighsLogType("kVerbose");
  public final static HighsLogType kWarning = new HighsLogType("kWarning");
  public final static HighsLogType kError = new HighsLogType("kError");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsLogType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsLogType.class + " with value " + swigValue);
  }

  private HighsLogType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsLogType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsLogType(String swigName, HighsLogType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsLogType[] swigValues = { kInfo, kDetailed, kVerbose, kWarning, kError };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

