/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsOptionType {
  public final static HighsOptionType kBool = new HighsOptionType("kBool", highsJNI.HighsOptionType_kBool_get());
  public final static HighsOptionType kInt = new HighsOptionType("kInt");
  public final static HighsOptionType kDouble = new HighsOptionType("kDouble");
  public final static HighsOptionType kString = new HighsOptionType("kString");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsOptionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsOptionType.class + " with value " + swigValue);
  }

  private HighsOptionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsOptionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsOptionType(String swigName, HighsOptionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsOptionType[] swigValues = { kBool, kInt, kDouble, kString };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

