/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsAnalysisLevel {
  public final static HighsAnalysisLevel kHighsAnalysisLevelNone = new HighsAnalysisLevel("kHighsAnalysisLevelNone", highsJNI.kHighsAnalysisLevelNone_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelModelData = new HighsAnalysisLevel("kHighsAnalysisLevelModelData", highsJNI.kHighsAnalysisLevelModelData_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelSolverSummaryData = new HighsAnalysisLevel("kHighsAnalysisLevelSolverSummaryData", highsJNI.kHighsAnalysisLevelSolverSummaryData_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelSolverRuntimeData = new HighsAnalysisLevel("kHighsAnalysisLevelSolverRuntimeData", highsJNI.kHighsAnalysisLevelSolverRuntimeData_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelSolverTime = new HighsAnalysisLevel("kHighsAnalysisLevelSolverTime", highsJNI.kHighsAnalysisLevelSolverTime_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelNlaData = new HighsAnalysisLevel("kHighsAnalysisLevelNlaData", highsJNI.kHighsAnalysisLevelNlaData_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelNlaTime = new HighsAnalysisLevel("kHighsAnalysisLevelNlaTime", highsJNI.kHighsAnalysisLevelNlaTime_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelMipData = new HighsAnalysisLevel("kHighsAnalysisLevelMipData", highsJNI.kHighsAnalysisLevelMipData_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelMipTime = new HighsAnalysisLevel("kHighsAnalysisLevelMipTime", highsJNI.kHighsAnalysisLevelMipTime_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelMin = new HighsAnalysisLevel("kHighsAnalysisLevelMin", highsJNI.kHighsAnalysisLevelMin_get());
  public final static HighsAnalysisLevel kHighsAnalysisLevelMax = new HighsAnalysisLevel("kHighsAnalysisLevelMax", highsJNI.kHighsAnalysisLevelMax_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsAnalysisLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsAnalysisLevel.class + " with value " + swigValue);
  }

  private HighsAnalysisLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsAnalysisLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsAnalysisLevel(String swigName, HighsAnalysisLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsAnalysisLevel[] swigValues = { kHighsAnalysisLevelNone, kHighsAnalysisLevelModelData, kHighsAnalysisLevelSolverSummaryData, kHighsAnalysisLevelSolverRuntimeData, kHighsAnalysisLevelSolverTime, kHighsAnalysisLevelNlaData, kHighsAnalysisLevelNlaTime, kHighsAnalysisLevelMipData, kHighsAnalysisLevelMipTime, kHighsAnalysisLevelMin, kHighsAnalysisLevelMax };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

