/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsModelStatus {
  public final static HighsModelStatus kNotset = new HighsModelStatus("kNotset", highsJNI.HighsModelStatus_kNotset_get());
  public final static HighsModelStatus kLoadError = new HighsModelStatus("kLoadError");
  public final static HighsModelStatus kModelError = new HighsModelStatus("kModelError");
  public final static HighsModelStatus kPresolveError = new HighsModelStatus("kPresolveError");
  public final static HighsModelStatus kSolveError = new HighsModelStatus("kSolveError");
  public final static HighsModelStatus kPostsolveError = new HighsModelStatus("kPostsolveError");
  public final static HighsModelStatus kModelEmpty = new HighsModelStatus("kModelEmpty");
  public final static HighsModelStatus kOptimal = new HighsModelStatus("kOptimal");
  public final static HighsModelStatus kInfeasible = new HighsModelStatus("kInfeasible");
  public final static HighsModelStatus kUnboundedOrInfeasible = new HighsModelStatus("kUnboundedOrInfeasible");
  public final static HighsModelStatus kUnbounded = new HighsModelStatus("kUnbounded");
  public final static HighsModelStatus kObjectiveBound = new HighsModelStatus("kObjectiveBound");
  public final static HighsModelStatus kObjectiveTarget = new HighsModelStatus("kObjectiveTarget");
  public final static HighsModelStatus kTimeLimit = new HighsModelStatus("kTimeLimit");
  public final static HighsModelStatus kIterationLimit = new HighsModelStatus("kIterationLimit");
  public final static HighsModelStatus kUnknown = new HighsModelStatus("kUnknown");
  public final static HighsModelStatus kSolutionLimit = new HighsModelStatus("kSolutionLimit");
  public final static HighsModelStatus kInterrupt = new HighsModelStatus("kInterrupt");
  public final static HighsModelStatus kMemoryLimit = new HighsModelStatus("kMemoryLimit");
  public final static HighsModelStatus kHighsInterrupt = new HighsModelStatus("kHighsInterrupt");
  public final static HighsModelStatus kMin = new HighsModelStatus("kMin", highsJNI.HighsModelStatus_kMin_get());
  public final static HighsModelStatus kMax = new HighsModelStatus("kMax", highsJNI.HighsModelStatus_kMax_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsModelStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsModelStatus.class + " with value " + swigValue);
  }

  private HighsModelStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsModelStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsModelStatus(String swigName, HighsModelStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsModelStatus[] swigValues = { kNotset, kLoadError, kModelError, kPresolveError, kSolveError, kPostsolveError, kModelEmpty, kOptimal, kInfeasible, kUnboundedOrInfeasible, kUnbounded, kObjectiveBound, kObjectiveTarget, kTimeLimit, kIterationLimit, kUnknown, kSolutionLimit, kInterrupt, kMemoryLimit, kHighsInterrupt, kMin, kMax };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

