/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HighsUserScaleData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HighsUserScaleData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighsUserScaleData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HighsUserScaleData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HighsUserScaleData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUser_objective_scale(int value) {
    highsJNI.HighsUserScaleData_user_objective_scale_set(swigCPtr, this, value);
  }

  public int getUser_objective_scale() {
    return highsJNI.HighsUserScaleData_user_objective_scale_get(swigCPtr, this);
  }

  public void setUser_bound_scale(int value) {
    highsJNI.HighsUserScaleData_user_bound_scale_set(swigCPtr, this, value);
  }

  public int getUser_bound_scale() {
    return highsJNI.HighsUserScaleData_user_bound_scale_get(swigCPtr, this);
  }

  public void setInfinite_cost(double value) {
    highsJNI.HighsUserScaleData_infinite_cost_set(swigCPtr, this, value);
  }

  public double getInfinite_cost() {
    return highsJNI.HighsUserScaleData_infinite_cost_get(swigCPtr, this);
  }

  public void setInfinite_bound(double value) {
    highsJNI.HighsUserScaleData_infinite_bound_set(swigCPtr, this, value);
  }

  public double getInfinite_bound() {
    return highsJNI.HighsUserScaleData_infinite_bound_get(swigCPtr, this);
  }

  public void setSmall_matrix_value(double value) {
    highsJNI.HighsUserScaleData_small_matrix_value_set(swigCPtr, this, value);
  }

  public double getSmall_matrix_value() {
    return highsJNI.HighsUserScaleData_small_matrix_value_get(swigCPtr, this);
  }

  public void setLarge_matrix_value(double value) {
    highsJNI.HighsUserScaleData_large_matrix_value_set(swigCPtr, this, value);
  }

  public double getLarge_matrix_value() {
    return highsJNI.HighsUserScaleData_large_matrix_value_get(swigCPtr, this);
  }

  public void setNum_infinite_costs(int value) {
    highsJNI.HighsUserScaleData_num_infinite_costs_set(swigCPtr, this, value);
  }

  public int getNum_infinite_costs() {
    return highsJNI.HighsUserScaleData_num_infinite_costs_get(swigCPtr, this);
  }

  public void setNum_infinite_hessian_values(int value) {
    highsJNI.HighsUserScaleData_num_infinite_hessian_values_set(swigCPtr, this, value);
  }

  public int getNum_infinite_hessian_values() {
    return highsJNI.HighsUserScaleData_num_infinite_hessian_values_get(swigCPtr, this);
  }

  public void setNum_infinite_col_bounds(int value) {
    highsJNI.HighsUserScaleData_num_infinite_col_bounds_set(swigCPtr, this, value);
  }

  public int getNum_infinite_col_bounds() {
    return highsJNI.HighsUserScaleData_num_infinite_col_bounds_get(swigCPtr, this);
  }

  public void setNum_infinite_row_bounds(int value) {
    highsJNI.HighsUserScaleData_num_infinite_row_bounds_set(swigCPtr, this, value);
  }

  public int getNum_infinite_row_bounds() {
    return highsJNI.HighsUserScaleData_num_infinite_row_bounds_get(swigCPtr, this);
  }

  public void setNum_small_matrix_values(int value) {
    highsJNI.HighsUserScaleData_num_small_matrix_values_set(swigCPtr, this, value);
  }

  public int getNum_small_matrix_values() {
    return highsJNI.HighsUserScaleData_num_small_matrix_values_get(swigCPtr, this);
  }

  public void setNum_large_matrix_values(int value) {
    highsJNI.HighsUserScaleData_num_large_matrix_values_set(swigCPtr, this, value);
  }

  public int getNum_large_matrix_values() {
    return highsJNI.HighsUserScaleData_num_large_matrix_values_get(swigCPtr, this);
  }

  public void setSuggested_user_objective_scale(int value) {
    highsJNI.HighsUserScaleData_suggested_user_objective_scale_set(swigCPtr, this, value);
  }

  public int getSuggested_user_objective_scale() {
    return highsJNI.HighsUserScaleData_suggested_user_objective_scale_get(swigCPtr, this);
  }

  public void setSuggested_user_bound_scale(int value) {
    highsJNI.HighsUserScaleData_suggested_user_bound_scale_set(swigCPtr, this, value);
  }

  public int getSuggested_user_bound_scale() {
    return highsJNI.HighsUserScaleData_suggested_user_bound_scale_get(swigCPtr, this);
  }

  public void setApplied(boolean value) {
    highsJNI.HighsUserScaleData_applied_set(swigCPtr, this, value);
  }

  public boolean getApplied() {
    return highsJNI.HighsUserScaleData_applied_get(swigCPtr, this);
  }

  public void initialise(int user_objective_scale_, int user_bound_scale_, double infinite_cost_, double infinite_bound_, double small_matrix_value_, double large_matrix_value_) {
    highsJNI.HighsUserScaleData_initialise(swigCPtr, this, user_objective_scale_, user_bound_scale_, infinite_cost_, infinite_bound_, small_matrix_value_, large_matrix_value_);
  }

  public boolean scaleError(SWIGTYPE_p_std__string message) {
    return highsJNI.HighsUserScaleData_scaleError(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(message));
  }

  public boolean scaleWarning(SWIGTYPE_p_std__string message) {
    return highsJNI.HighsUserScaleData_scaleWarning(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(message));
  }

  public HighsUserScaleData() {
    this(highsJNI.new_HighsUserScaleData(), true);
  }

}
