/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsBasisStatus {
  public final static HighsBasisStatus kLower = new HighsBasisStatus("kLower", highsJNI.HighsBasisStatus_kLower_get());
  public final static HighsBasisStatus kBasic = new HighsBasisStatus("kBasic");
  public final static HighsBasisStatus kUpper = new HighsBasisStatus("kUpper");
  public final static HighsBasisStatus kZero = new HighsBasisStatus("kZero");
  public final static HighsBasisStatus kNonbasic = new HighsBasisStatus("kNonbasic");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsBasisStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsBasisStatus.class + " with value " + swigValue);
  }

  private HighsBasisStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsBasisStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsBasisStatus(String swigName, HighsBasisStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsBasisStatus[] swigValues = { kLower, kBasic, kUpper, kZero, kNonbasic };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

