/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class HighsPresolveStatus {
  public final static HighsPresolveStatus kNotPresolved = new HighsPresolveStatus("kNotPresolved", highsJNI.HighsPresolveStatus_kNotPresolved_get());
  public final static HighsPresolveStatus kNotReduced = new HighsPresolveStatus("kNotReduced");
  public final static HighsPresolveStatus kInfeasible = new HighsPresolveStatus("kInfeasible");
  public final static HighsPresolveStatus kUnboundedOrInfeasible = new HighsPresolveStatus("kUnboundedOrInfeasible");
  public final static HighsPresolveStatus kReduced = new HighsPresolveStatus("kReduced");
  public final static HighsPresolveStatus kReducedToEmpty = new HighsPresolveStatus("kReducedToEmpty");
  public final static HighsPresolveStatus kTimeout = new HighsPresolveStatus("kTimeout");
  public final static HighsPresolveStatus kNullError = new HighsPresolveStatus("kNullError");
  public final static HighsPresolveStatus kOptionsError = new HighsPresolveStatus("kOptionsError");
  public final static HighsPresolveStatus kNotSet = new HighsPresolveStatus("kNotSet");
  public final static HighsPresolveStatus kOutOfMemory = new HighsPresolveStatus("kOutOfMemory");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HighsPresolveStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HighsPresolveStatus.class + " with value " + swigValue);
  }

  private HighsPresolveStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HighsPresolveStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HighsPresolveStatus(String swigName, HighsPresolveStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HighsPresolveStatus[] swigValues = { kNotPresolved, kNotReduced, kInfeasible, kUnboundedOrInfeasible, kReduced, kReducedToEmpty, kTimeout, kNullError, kOptionsError, kNotSet, kOutOfMemory };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

