/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HighsSubSolverCallTime {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HighsSubSolverCallTime(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighsSubSolverCallTime obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HighsSubSolverCallTime obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HighsSubSolverCallTime(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(SWIGTYPE_p_std__vectorT_std__string_t value) {
    highsJNI.HighsSubSolverCallTime_name_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getName() {
    long cPtr = highsJNI.HighsSubSolverCallTime_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public void setNum_call(SWIGTYPE_p_std__vectorT_int_t value) {
    highsJNI.HighsSubSolverCallTime_num_call_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_int_t getNum_call() {
    long cPtr = highsJNI.HighsSubSolverCallTime_num_call_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_int_t(cPtr, false);
  }

  public void setRun_time(DoubleVector value) {
    highsJNI.HighsSubSolverCallTime_run_time_set(swigCPtr, this, DoubleVector.getCPtr(value), value);
  }

  public DoubleVector getRun_time() {
    long cPtr = highsJNI.HighsSubSolverCallTime_run_time_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleVector(cPtr, false);
  }

  public void initialise() {
    highsJNI.HighsSubSolverCallTime_initialise(swigCPtr, this);
  }

  public void add(HighsSubSolverCallTime sub_solver_call_time, boolean analytic_centre) {
    highsJNI.HighsSubSolverCallTime_add__SWIG_0(swigCPtr, this, HighsSubSolverCallTime.getCPtr(sub_solver_call_time), sub_solver_call_time, analytic_centre);
  }

  public void add(HighsSubSolverCallTime sub_solver_call_time) {
    highsJNI.HighsSubSolverCallTime_add__SWIG_1(swigCPtr, this, HighsSubSolverCallTime.getCPtr(sub_solver_call_time), sub_solver_call_time);
  }

  public HighsSubSolverCallTime() {
    this(highsJNI.new_HighsSubSolverCallTime(), true);
  }

}
