/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class HotStart {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HotStart(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HotStart obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(HotStart obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_HotStart(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValid(boolean value) {
    highsJNI.HotStart_valid_set(swigCPtr, this, value);
  }

  public boolean getValid() {
    return highsJNI.HotStart_valid_get(swigCPtr, this);
  }

  public void setRefactor_info(RefactorInfo value) {
    highsJNI.HotStart_refactor_info_set(swigCPtr, this, RefactorInfo.getCPtr(value), value);
  }

  public RefactorInfo getRefactor_info() {
    long cPtr = highsJNI.HotStart_refactor_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RefactorInfo(cPtr, false);
  }

  public void setNonbasicMove(SWIGTYPE_p_std__vectorT_int8_t_t value) {
    highsJNI.HotStart_nonbasicMove_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_int8_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_int8_t_t getNonbasicMove() {
    long cPtr = highsJNI.HotStart_nonbasicMove_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_int8_t_t(cPtr, false);
  }

  public HotStart() {
    this(highsJNI.new_HotStart(), true);
  }

}
