/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class IisStatus {
  public final static IisStatus kIisStatusMin = new IisStatus("kIisStatusMin", highsJNI.kIisStatusMin_get());
  public final static IisStatus kIisStatusInConflict = new IisStatus("kIisStatusInConflict", highsJNI.kIisStatusInConflict_get());
  public final static IisStatus kIisStatusNotInConflict = new IisStatus("kIisStatusNotInConflict");
  public final static IisStatus kIisStatusMaybeInConflict = new IisStatus("kIisStatusMaybeInConflict");
  public final static IisStatus kIisStatusMax = new IisStatus("kIisStatusMax", highsJNI.kIisStatusMax_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IisStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IisStatus.class + " with value " + swigValue);
  }

  private IisStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IisStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IisStatus(String swigName, IisStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IisStatus[] swigValues = { kIisStatusMin, kIisStatusInConflict, kIisStatusNotInConflict, kIisStatusMaybeInConflict, kIisStatusMax };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

