/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class IisStrategy {
  public final static IisStrategy kIisStrategyMin = new IisStrategy("kIisStrategyMin", highsJNI.kIisStrategyMin_get());
  public final static IisStrategy kIisStrategyLight = new IisStrategy("kIisStrategyLight", highsJNI.kIisStrategyLight_get());
  public final static IisStrategy kIisStrategyFromLpRowPriority = new IisStrategy("kIisStrategyFromLpRowPriority");
  public final static IisStrategy kIisStrategyFromLpColPriority = new IisStrategy("kIisStrategyFromLpColPriority");
  public final static IisStrategy kIisStrategyMax = new IisStrategy("kIisStrategyMax", highsJNI.kIisStrategyMax_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IisStrategy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IisStrategy.class + " with value " + swigValue);
  }

  private IisStrategy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IisStrategy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IisStrategy(String swigName, IisStrategy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IisStrategy[] swigValues = { kIisStrategyMin, kIisStrategyLight, kIisStrategyFromLpRowPriority, kIisStrategyFromLpColPriority, kIisStrategyMax };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

