/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class IntegerArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntegerArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntegerArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IntegerArray obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_IntegerArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntegerArray(long nelements) {
    this(highsJNI.new_IntegerArray(nelements), true);
  }

  public int getitem(long index) {
    return highsJNI.IntegerArray_getitem(swigCPtr, this, index);
  }

  public void setitem(long index, int value) {
    highsJNI.IntegerArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_int cast() {
    long cPtr = highsJNI.IntegerArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static IntegerArray frompointer(SWIGTYPE_p_int t) {
    long cPtr = highsJNI.IntegerArray_frompointer(SWIGTYPE_p_int.getCPtr(t));
    return (cPtr == 0) ? null : new IntegerArray(cPtr, false);
  }

}
