/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class IpxDualizeStrategy {
  public final static IpxDualizeStrategy kIpxDualizeStrategyOff = new IpxDualizeStrategy("kIpxDualizeStrategyOff", highsJNI.kIpxDualizeStrategyOff_get());
  public final static IpxDualizeStrategy kIpxDualizeStrategyChoose = new IpxDualizeStrategy("kIpxDualizeStrategyChoose", highsJNI.kIpxDualizeStrategyChoose_get());
  public final static IpxDualizeStrategy kIpxDualizeStrategyOn = new IpxDualizeStrategy("kIpxDualizeStrategyOn", highsJNI.kIpxDualizeStrategyOn_get());
  public final static IpxDualizeStrategy kIpxDualizeStrategyLukas = new IpxDualizeStrategy("kIpxDualizeStrategyLukas");
  public final static IpxDualizeStrategy kIpxDualizeStrategyFilippo = new IpxDualizeStrategy("kIpxDualizeStrategyFilippo");
  public final static IpxDualizeStrategy kIpxDualizeStrategyMin = new IpxDualizeStrategy("kIpxDualizeStrategyMin", highsJNI.kIpxDualizeStrategyMin_get());
  public final static IpxDualizeStrategy kIpxDualizeStrategyMax = new IpxDualizeStrategy("kIpxDualizeStrategyMax", highsJNI.kIpxDualizeStrategyMax_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IpxDualizeStrategy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IpxDualizeStrategy.class + " with value " + swigValue);
  }

  private IpxDualizeStrategy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IpxDualizeStrategy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IpxDualizeStrategy(String swigName, IpxDualizeStrategy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IpxDualizeStrategy[] swigValues = { kIpxDualizeStrategyOff, kIpxDualizeStrategyChoose, kIpxDualizeStrategyOn, kIpxDualizeStrategyLukas, kIpxDualizeStrategyFilippo, kIpxDualizeStrategyMin, kIpxDualizeStrategyMax };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

