/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class MatrixFormat {
  public final static MatrixFormat kColwise = new MatrixFormat("kColwise", highsJNI.MatrixFormat_kColwise_get());
  public final static MatrixFormat kRowwise = new MatrixFormat("kRowwise");
  public final static MatrixFormat kRowwisePartitioned = new MatrixFormat("kRowwisePartitioned");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MatrixFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MatrixFormat.class + " with value " + swigValue);
  }

  private MatrixFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MatrixFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MatrixFormat(String swigName, MatrixFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MatrixFormat[] swigValues = { kColwise, kRowwise, kRowwisePartitioned };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

