/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class ObjSense {
  public final static ObjSense kMinimize = new ObjSense("kMinimize", highsJNI.ObjSense_kMinimize_get());
  public final static ObjSense kMaximize = new ObjSense("kMaximize", highsJNI.ObjSense_kMaximize_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjSense swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjSense.class + " with value " + swigValue);
  }

  private ObjSense(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjSense(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjSense(String swigName, ObjSense swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjSense[] swigValues = { kMinimize, kMaximize };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

