/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class OptionOffChooseOn {
  public final static OptionOffChooseOn kHighsOptionOff = new OptionOffChooseOn("kHighsOptionOff", highsJNI.kHighsOptionOff_get());
  public final static OptionOffChooseOn kHighsOptionChoose = new OptionOffChooseOn("kHighsOptionChoose");
  public final static OptionOffChooseOn kHighsOptionOn = new OptionOffChooseOn("kHighsOptionOn");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OptionOffChooseOn swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OptionOffChooseOn.class + " with value " + swigValue);
  }

  private OptionOffChooseOn(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OptionOffChooseOn(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OptionOffChooseOn(String swigName, OptionOffChooseOn swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OptionOffChooseOn[] swigValues = { kHighsOptionOff, kHighsOptionChoose, kHighsOptionOn };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

