/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public class RefactorInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RefactorInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RefactorInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RefactorInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        highsJNI.delete_RefactorInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUse(boolean value) {
    highsJNI.RefactorInfo_use_set(swigCPtr, this, value);
  }

  public boolean getUse() {
    return highsJNI.RefactorInfo_use_get(swigCPtr, this);
  }

  public void setPivot_row(SWIGTYPE_p_std__vectorT_int_t value) {
    highsJNI.RefactorInfo_pivot_row_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_int_t getPivot_row() {
    long cPtr = highsJNI.RefactorInfo_pivot_row_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_int_t(cPtr, false);
  }

  public void setPivot_var(SWIGTYPE_p_std__vectorT_int_t value) {
    highsJNI.RefactorInfo_pivot_var_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_int_t getPivot_var() {
    long cPtr = highsJNI.RefactorInfo_pivot_var_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_int_t(cPtr, false);
  }

  public void setPivot_type(SWIGTYPE_p_std__vectorT_int8_t_t value) {
    highsJNI.RefactorInfo_pivot_type_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_int8_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_int8_t_t getPivot_type() {
    long cPtr = highsJNI.RefactorInfo_pivot_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_int8_t_t(cPtr, false);
  }

  public void setBuild_synthetic_tick(double value) {
    highsJNI.RefactorInfo_build_synthetic_tick_set(swigCPtr, this, value);
  }

  public double getBuild_synthetic_tick() {
    return highsJNI.RefactorInfo_build_synthetic_tick_get(swigCPtr, this);
  }

  public void clear() {
    highsJNI.RefactorInfo_clear(swigCPtr, this);
  }

  public RefactorInfo() {
    this(highsJNI.new_RefactorInfo(), true);
  }

}
