/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package highs;

public final class SubSolverIndex {
  public final static SubSolverIndex kSubSolverMip = new SubSolverIndex("kSubSolverMip", highsJNI.kSubSolverMip_get());
  public final static SubSolverIndex kSubSolverSimplexBasis = new SubSolverIndex("kSubSolverSimplexBasis");
  public final static SubSolverIndex kSubSolverSimplexNoBasis = new SubSolverIndex("kSubSolverSimplexNoBasis");
  public final static SubSolverIndex kSubSolverHipo = new SubSolverIndex("kSubSolverHipo");
  public final static SubSolverIndex kSubSolverIpx = new SubSolverIndex("kSubSolverIpx");
  public final static SubSolverIndex kSubSolverHipoAc = new SubSolverIndex("kSubSolverHipoAc");
  public final static SubSolverIndex kSubSolverIpxAc = new SubSolverIndex("kSubSolverIpxAc");
  public final static SubSolverIndex kSubSolverPdlp = new SubSolverIndex("kSubSolverPdlp");
  public final static SubSolverIndex kSubSolverQpAsm = new SubSolverIndex("kSubSolverQpAsm");
  public final static SubSolverIndex kSubSolverSubMip = new SubSolverIndex("kSubSolverSubMip");
  public final static SubSolverIndex kSubSolverCount = new SubSolverIndex("kSubSolverCount");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SubSolverIndex swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SubSolverIndex.class + " with value " + swigValue);
  }

  private SubSolverIndex(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SubSolverIndex(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SubSolverIndex(String swigName, SubSolverIndex swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SubSolverIndex[] swigValues = { kSubSolverMip, kSubSolverSimplexBasis, kSubSolverSimplexNoBasis, kSubSolverHipo, kSubSolverIpx, kSubSolverHipoAc, kSubSolverIpxAc, kSubSolverPdlp, kSubSolverQpAsm, kSubSolverSubMip, kSubSolverCount };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

